def _key(title, year):
    return "%s|%s" % ((title or "").strip().lower(), year or "")


REAL_POSTER_URLS = {
    _key("Toy Story", 1995): "https://image.tmdb.org/t/p/original/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    _key("Jumanji", 1995): "https://image.tmdb.org/t/p/original/iWV47r6kFneCiApgrMII5HSkfHw.jpg",
    _key("Heat", 1995): "https://image.tmdb.org/t/p/original/e09dLw1Ljtccd2P4NsuUvVtS5du.jpg",
    _key("Sabrina", 1995): "https://image.tmdb.org/t/p/original/i8PbLJDPU7vCwwscWD625oHbJy.jpg",
    _key("GoldenEye", 1995): "https://image.tmdb.org/t/p/original/yObOAYFIHXHkFPQ3jhgkN2ezaD.jpg",
    _key("The American President", 1995): "https://image.tmdb.org/t/p/original/4rRfZz8YnHNRr16t3CFcJrPdXHi.jpg",
    _key("American President, The", 1995): "https://image.tmdb.org/t/p/original/4rRfZz8YnHNRr16t3CFcJrPdXHi.jpg",
    _key("Casino", 1995): "https://image.tmdb.org/t/p/original/gziIkUSnYuj9ChCi8qOu2ZunpSC.jpg",
    _key("Sense and Sensibility", 1995): "https://image.tmdb.org/t/p/original/cBK2yL3HqhFvIVd7lLtazWlRZPR.jpg",
    _key("Four Rooms", 1995): "https://image.tmdb.org/t/p/original/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg",
    _key("Ace Ventura: When Nature Calls", 1995): "https://image.tmdb.org/t/p/original/wcinCf1ov2D6M3P7BBZkzQFOiIb.jpg",
    _key("Get Shorty", 1995): "https://image.tmdb.org/t/p/original/r82SdPhg4fnIcLt0ogIjQxqjdcO.jpg",
    _key("Leaving Las Vegas", 1995): "https://image.tmdb.org/t/p/original/wTrFpGe3U65kXTldIUxuM2hmOAK.jpg",
    _key("Twelve Monkeys", 1995): "https://image.tmdb.org/t/p/original/gt3iyguaCIw8DpQZI1LIN5TohM2.jpg",
    _key("12 Monkeys (Twelve Monkeys)", 1995): "https://image.tmdb.org/t/p/original/gt3iyguaCIw8DpQZI1LIN5TohM2.jpg",
    _key("Babe", 1995): "https://image.tmdb.org/t/p/original/zKuQMtnbVTz9DsOnOJmlW71v4qH.jpg",
    _key("Dead Man Walking", 1995): "https://image.tmdb.org/t/p/original/eShxyjhWoFl3BwsuEmVsr4nLaMZ.jpg",
    _key("Clueless", 1995): "https://image.tmdb.org/t/p/original/8AwVTcgpTnmeOs4TdTWqcFDXEsA.jpg",
    _key("Se7en", 1995): "https://image.tmdb.org/t/p/original/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    _key("Seven (Se7en)", 1995): "https://image.tmdb.org/t/p/original/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    _key("Seven (a.k.a. Se7en)", 1995): "https://image.tmdb.org/t/p/original/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    _key("The Usual Suspects", 1995): "https://image.tmdb.org/t/p/original/99X2SgyFunJFXGAYnDv3sb9pnUD.jpg",
    _key("Usual Suspects, The", 1995): "https://image.tmdb.org/t/p/original/99X2SgyFunJFXGAYnDv3sb9pnUD.jpg",
    _key("Braveheart", 1995): "https://image.tmdb.org/t/p/original/or1gBugydmjToAEq7OZY0owwFk.jpg",
    _key("Apollo 13", 1995): "https://image.tmdb.org/t/p/original/tVeKscCm2fY1xDXZk8PgnZ87h9S.jpg",
    _key("Star Wars: Episode IV - A New Hope", 1977): "https://image.tmdb.org/t/p/original/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    _key("Star Wars: Episode IV - A New Hope (a.k.a. Star Wars)", 1977): "https://image.tmdb.org/t/p/original/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    _key("Pulp Fiction", 1994): "https://image.tmdb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    _key("The Shawshank Redemption", 1994): "https://image.tmdb.org/t/p/original/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    _key("Shawshank Redemption, The", 1994): "https://image.tmdb.org/t/p/original/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    _key("Forrest Gump", 1994): "https://image.tmdb.org/t/p/original/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg",
    _key("The Lion King", 1994): "https://image.tmdb.org/t/p/original/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    _key("Lion King, The", 1994): "https://image.tmdb.org/t/p/original/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    _key("Jurassic Park", 1993): "https://image.tmdb.org/t/p/original/maFjKnJ62hDQ9E66dKqDZgbUy0H.jpg",
    _key("Schindler's List", 1993): "https://image.tmdb.org/t/p/original/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    _key("Fargo", 1996): "https://image.tmdb.org/t/p/original/rt7cpEr1uP6RTZykBFhBTcRaKvG.jpg",
    _key("Aladdin", 1992): "https://image.tmdb.org/t/p/original/eLFfl7vS8dkeG1hKp5mwbm37V83.jpg",
    _key("Terminator 2: Judgment Day", 1991): "https://image.tmdb.org/t/p/original/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
    _key("Dances with Wolves", 1990): "https://image.tmdb.org/t/p/original/hw0ZEHAaTqTxSXGVwUFX7uvanSA.jpg",
    _key("The Fugitive", 1993): "https://image.tmdb.org/t/p/original/b3rEtLKyOnF89mcK75GXDXdmOEf.jpg",
    _key("Fugitive, The", 1993): "https://image.tmdb.org/t/p/original/b3rEtLKyOnF89mcK75GXDXdmOEf.jpg",
    _key("Batman", 1989): "https://image.tmdb.org/t/p/original/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg",
    _key("Independence Day", 1996): "https://image.tmdb.org/t/p/original/p0BPQGSPoSa8Ml0DAf2mB2kCU0R.jpg",
    _key("Independence Day (a.k.a. ID4)", 1996): "https://image.tmdb.org/t/p/original/p0BPQGSPoSa8Ml0DAf2mB2kCU0R.jpg",
    _key("True Lies", 1994): "https://image.tmdb.org/t/p/original/pweFTnzzTfGK68woSVkiTgjL4N.jpg",
    _key("Speed", 1994): "https://image.tmdb.org/t/p/original/o1Zs7VaS9y2GYH9CLeWxaVLWd3x.jpg",
    _key("Mission: Impossible", 1996): "https://image.tmdb.org/t/p/original/l5uxY5m5OInWpcExIpKG6AR3rgL.jpg",
    _key("Ace Ventura: Pet Detective", 1994): "https://image.tmdb.org/t/p/original/pqiRuETmuSybfnVZ7qyeoXhQyN1.jpg",
    _key("Beauty and the Beast", 1991): "https://image.tmdb.org/t/p/original/hUJ0UvQ5tgE2Z9WpfuduVSdiCiU.jpg",
    _key("The Silence of the Lambs", 1991): "https://image.tmdb.org/t/p/original/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    _key("Silence of the Lambs, The", 1991): "https://image.tmdb.org/t/p/original/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    _key("The Godfather", 1972): "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    _key("Godfather, The", 1972): "https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    _key("Star Wars: Episode V - The Empire Strikes Back", 1980): "https://image.tmdb.org/t/p/original/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
    _key("Raiders of the Lost Ark", 1981): "https://image.tmdb.org/t/p/original/ceG9VzoRAVGwivFU403Wc3AHRys.jpg",
    _key("Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark)", 1981): "https://image.tmdb.org/t/p/original/ceG9VzoRAVGwivFU403Wc3AHRys.jpg",
    _key("Star Wars: Episode VI - Return of the Jedi", 1983): "https://image.tmdb.org/t/p/original/jQYlydvHm3kUix1f8prMucrplhm.jpg",
    _key("Back to the Future", 1985): "https://image.tmdb.org/t/p/original/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",
    _key("Saving Private Ryan", 1998): "https://image.tmdb.org/t/p/original/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
    _key("Inception", 2010): "https://image.tmdb.org/t/p/original/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
    _key("The Dark Knight", 2008): "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    _key("La La Land", 2016): "https://image.tmdb.org/t/p/original/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    _key("Spirited Away", 2001): "https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    _key("Interstellar", 2014): "https://image.tmdb.org/t/p/original/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    _key("Your Name", 2016): "https://image.tmdb.org/t/p/original/q719jXXEzOoYaps6babgKnONONX.jpg",
    _key("Coco", 2017): "https://image.tmdb.org/t/p/original/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg",
    _key("Parasite", 2019): "https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    _key("Whiplash", 2014): "https://image.tmdb.org/t/p/original/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    _key("The Lord of the Rings: The Fellowship of the Ring", 2001): "https://image.tmdb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    _key("Lord of the Rings: The Fellowship of the Ring, The", 2001): "https://image.tmdb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    _key("Spider-Man: Into the Spider-Verse", 2018): "https://image.tmdb.org/t/p/original/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    _key("Dune", 2021): "https://image.tmdb.org/t/p/original/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg",
    _key("The Grand Budapest Hotel", 2014): "https://image.tmdb.org/t/p/original/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    _key("Pride & Prejudice", 2005): "https://image.tmdb.org/t/p/original/o8UhmEbWPHmTUxP0lMuCoqNkbB3.jpg",
    _key("Mad Max: Fury Road", 2015): "https://image.tmdb.org/t/p/original/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    _key("The Truman Show", 1998): "https://image.tmdb.org/t/p/original/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    _key("Blade Runner 2049", 2017): "https://image.tmdb.org/t/p/original/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    _key("Soul", 2020): "https://image.tmdb.org/t/p/original/6jmppcaubzLF8wkXM36ganVISCo.jpg",
    _key("Avengers: Endgame", 2019): "https://image.tmdb.org/t/p/original/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    _key("Little Women", 2019): "https://image.tmdb.org/t/p/original/yn5ihODtZ7ofn8pDYfxCmxh8AXI.jpg",
    _key("Everything Everywhere All at Once", 2022): "https://image.tmdb.org/t/p/original/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    _key("The Social Network", 2010): "https://image.tmdb.org/t/p/original/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    _key("Howl's Moving Castle", 2004): "https://image.tmdb.org/t/p/original/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg",
    _key("American Beauty", 1999): "https://image.tmdb.org/t/p/original/wby9315QzVKdW9BonAefg8jGTTb.jpg",
    _key("The Matrix", 1999): "https://image.tmdb.org/t/p/original/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",
    _key("Matrix, The", 1999): "https://image.tmdb.org/t/p/original/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",
    _key("Fight Club", 1999): "https://image.tmdb.org/t/p/original/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",
    _key("Memento", 2000): "https://image.tmdb.org/t/p/original/fKTPH2WvH8nHTXeBYBVhawtRqtR.jpg",
    _key("The Sixth Sense", 1999): "https://image.tmdb.org/t/p/original/vOyfUXNFSnaTk7Vk5AjpsKTUWsu.jpg",
    _key("Sixth Sense, The", 1999): "https://image.tmdb.org/t/p/original/vOyfUXNFSnaTk7Vk5AjpsKTUWsu.jpg",
    _key("Men in Black", 1997): "https://image.tmdb.org/t/p/original/uLOmOF5IzWoyrgIF5MfUnh5pa1X.jpg",
    _key("Pretty Woman", 1990): "https://image.tmdb.org/t/p/original/hVHUfT801LQATGd26VPzhorIYza.jpg",
    _key("Mrs. Doubtfire", 1993): "https://image.tmdb.org/t/p/original/3GogS4kCk9LjC74t0n8rHOYiYYS.jpg",
    _key("E.T. the Extra-Terrestrial", 1982): "https://image.tmdb.org/t/p/original/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg",
    _key("Terminator, The", 1984): "https://image.tmdb.org/t/p/original/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
    _key("Princess Bride, The", 1987): "https://image.tmdb.org/t/p/original/2FC9L9MrjBoGHYjYZjdWQdopVYb.jpg",
    _key("The Princess Bride", 1987): "https://image.tmdb.org/t/p/original/2FC9L9MrjBoGHYjYZjdWQdopVYb.jpg",
    _key("Good Will Hunting", 1997): "https://image.tmdb.org/t/p/original/z2FnLKpFi1HPO7BEJxdkv6hpJSU.jpg",
    _key("Titanic", 1997): "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    _key("Shrek", 2001): "https://image.tmdb.org/t/p/original/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
    _key("Monsters, Inc.", 2001): "https://image.tmdb.org/t/p/original/wFSpyMsp7H0ttERbxY7Trlv8xry.jpg",
    _key("Finding Nemo", 2003): "https://image.tmdb.org/t/p/original/5lc6nQc0VhWFYFbNv016xze8Jvy.jpg",
    _key("Gladiator", 2000): "https://image.tmdb.org/t/p/original/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg",
    _key("The Lord of the Rings: The Two Towers", 2002): "https://image.tmdb.org/t/p/original/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    _key("Lord of the Rings: The Two Towers, The", 2002): "https://image.tmdb.org/t/p/original/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    _key("The Lord of the Rings: The Return of the King", 2003): "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    _key("Lord of the Rings: The Return of the King, The", 2003): "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    _key("Pirates of the Caribbean: The Curse of the Black Pearl", 2003): "https://image.tmdb.org/t/p/original/kvDwL2gTf6yxujbsWbsGQB3Z9Wa.jpg",
    _key("Kill Bill: Vol. 1", 2003): "https://image.tmdb.org/t/p/original/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg",
    _key("Kill Bill: Vol. 2", 2004): "https://image.tmdb.org/t/p/original/2yhg0mZQMhDyvUQ4rG1IZ4oIA8L.jpg",
    _key("The Incredibles", 2004): "https://image.tmdb.org/t/p/original/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
    _key("Incredibles, The", 2004): "https://image.tmdb.org/t/p/original/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
    _key("Eternal Sunshine of the Spotless Mind", 2004): "https://image.tmdb.org/t/p/original/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    _key("Batman Begins", 2005): "https://image.tmdb.org/t/p/original/sPX89Td70IDDjVr85jdSBb4rWGr.jpg",
    _key("V for Vendetta", 2006): "https://image.tmdb.org/t/p/original/piZOwjyk1g51oPHonc7zaQY3WOv.jpg",
    _key("The Departed", 2006): "https://image.tmdb.org/t/p/original/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    _key("Departed, The", 2006): "https://image.tmdb.org/t/p/original/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    _key("No Country for Old Men", 2007): "https://image.tmdb.org/t/p/original/6d5XOczc226jECq0LIX0siKtgHR.jpg",
    _key("There Will Be Blood", 2007): "https://image.tmdb.org/t/p/original/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
    _key("WALL-E", 2008): "https://image.tmdb.org/t/p/original/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    _key("Up", 2009): "https://image.tmdb.org/t/p/original/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg",
    _key("Avatar", 2009): "https://image.tmdb.org/t/p/original/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg",
    _key("The Prestige", 2006): "https://image.tmdb.org/t/p/original/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
    _key("Prestige, The", 2006): "https://image.tmdb.org/t/p/original/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg",
    _key("The Green Mile", 1999): "https://image.tmdb.org/t/p/original/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    _key("Green Mile, The", 1999): "https://image.tmdb.org/t/p/original/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
}


def poster_url_for_movie(title, year, fallback_url):
    return REAL_POSTER_URLS.get(_key(title, year), fallback_url)
